# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

sudo: required
dist: trusty

language: c++

matrix:
    include:
      - compiler: gcc
        env: |
          USER_CONFIG="using gcc : : g++-4.8 -Werror --std=c++03 -fsanitize=address ;"
      - compiler: gcc
        env: |
          USER_CONFIG="using gcc : : g++-4.8 -Werror --std=c++11 -fsanitize=address ;"
      - compiler: clang
        env: |
          USER_CONFIG="using clang : : clang++ -Werror --std=c++03 -fsanitize=address ;"
      - compiler: clang
        env: |
          USER_CONFIG="using clang : : clang++ -Werror --std=c++11 -fsanitize=address ;"
      - compiler: clang
        env: |
          USER_CONFIG="using clang : : clang++ -Werror --std=c++11 -D_HAS_AUTO_PTR_ETC=0 ;"

before_script:
    - echo $USER_CONFIG > ~/user-config.jam
    - cat ~/user-config.jam
    - touch Jamroot.jam
    - export BOOST_VERSION=1.64.0
    - export BOOST_FILENAME=boost_1_64_0
    - export BOOST_ROOT=${HOME}/boost
    - |
        mkdir $HOME/download
        mkdir $HOME/extract
        cd $HOME/download
        if [ "$TRAVIS_EVENT_TYPE" == "cron" ]
        then
            if [ "$TRAVIS_BRANCH" == "master" ]
            then
                snapshot_branch=master
            else
                snapshot_branch=develop
            fi
            download_url=$(curl https://api.bintray.com/packages/boostorg/$snapshot_branch/snapshot/files |
                    python -c "import os.path, sys, json; x = json.load(sys.stdin); print '\n'.join(a['path'] for a in x if os.path.splitext(a['path'])[1] == '.bz2')" |
                    head -n 1 |
                    sed "s/^/http:\/\/dl.bintray.com\/boostorg\/$snapshot_branch\//")
        else
            download_url=https://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/${BOOST_FILENAME}.tar.bz2/download
        fi
        echo "Downloading ${download_url}"
        wget -O boost.tar.bz2 $download_url
        cd $HOME/extract
        tar -xjf $HOME/download/boost.tar.bz2
        mv * ${BOOST_ROOT}
    - rm -r ${BOOST_ROOT}/libs/functional
    - rm -r ${BOOST_ROOT}/boost/functional
    - cd ${BOOST_ROOT}/tools/build
    - mkdir ${HOME}/opt
    - ./bootstrap.sh
    - ./b2 install --prefix=$HOME/opt

script:
    - cd ${TRAVIS_BUILD_DIR}/test
    - ${HOME}/opt/bin/b2 -q include=${TRAVIS_BUILD_DIR}/include include=${BOOST_ROOT}
    - cd ${TRAVIS_BUILD_DIR}/hash/test
    - ${HOME}/opt/bin/b2 -q include=${TRAVIS_BUILD_DIR}/include include=${BOOST_ROOT}
    - cd ${TRAVIS_BUILD_DIR}/forward/test
    - ${HOME}/opt/bin/b2 -q include=${TRAVIS_BUILD_DIR}/include include=${BOOST_ROOT}
    - cd ${TRAVIS_BUILD_DIR}/factory/test
    - ${HOME}/opt/bin/b2 -q include=${TRAVIS_BUILD_DIR}/include include=${BOOST_ROOT}
    - cd ${TRAVIS_BUILD_DIR}/overloaded_function/test
    - ${HOME}/opt/bin/b2 -q include=${TRAVIS_BUILD_DIR}/include include=${BOOST_ROOT}
