# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Use Trusty to get a reasonably recent version of Boost.
sudo: required
dist: trusty

language: c++

addons:
    apt:
        packages:
            - libboost-dev
            - libboost-tools-dev

matrix:
    include:
      - compiler: gcc
        env: |
          USER_CONFIG="using gcc : : g++-4.8 -Werror --std=c++03 -fsanitize=address ;"
      - compiler: gcc
        env: |
          USER_CONFIG="using gcc : : g++-4.8 -Werror --std=c++11 -fsanitize=address ;"
      - compiler: clang
        env: |
          USER_CONFIG="using clang : : clang++ -Werror --std=c++03 -fsanitize=address ;"
      - compiler: clang
        env: |
          USER_CONFIG="using clang : : clang++ -Werror --std=c++11 -fsanitize=address ;"
      - compiler: clang
        env: |
          USER_CONFIG="using clang : : clang++ -Werror --std=c++11 -D_HAS_AUTO_PTR_ETC=0 ;"

before_script:
    - echo $USER_CONFIG > ~/user-config.jam
    - cat ~/user-config.jam
    - touch Jamroot.jam

script:
    - cd ${TRAVIS_BUILD_DIR}/test
    - bjam -q ${BJAM_TOOLSET} include=${TRAVIS_BUILD_DIR}/include
    - cd ${TRAVIS_BUILD_DIR}/hash/test
    - bjam -q ${BJAM_TOOLSET} include=${TRAVIS_BUILD_DIR}/include
    - cd ${TRAVIS_BUILD_DIR}/forward/test
    - bjam -q ${BJAM_TOOLSET} include=${TRAVIS_BUILD_DIR}/include
    - cd ${TRAVIS_BUILD_DIR}/factory/test
    - bjam -q ${BJAM_TOOLSET} include=${TRAVIS_BUILD_DIR}/include
    - cd ${TRAVIS_BUILD_DIR}/overloaded_function/test
    - bjam -q ${BJAM_TOOLSET} include=${TRAVIS_BUILD_DIR}/include
